const tierList = {
    '未定': [
        { name: 'Dahlia' },
        { name: 'frequent' },
        { name: 'GAME ON' },
        { name: 'Ghost Pulse' },
        { name: 'JUSTICE/GUILTY feat. Nana Takahashi & 709sec.' },
        { name: 'SOLAR ECLIPSE' },
        { name: `摩天楼` },
        { name: 'yellow head joe[L]' },
        { name: '恋する☆宇宙戦争っ!![L]' },
        { name: 'CODE:Ø[L]' },
        { name: '《PL|RAYER》' },
        { name: `電光` },
        { name: `Sirius` }
    ],
    '個人差F': [
        { name: `sakura storm` }
    ],
    '地力F': [
        { name: `Primitive Vibes` },
        { name: `Ristaccia` },
        { name: `snow storm[L]` },
        { name: `SPECIAL SUMMER CAMPAIGN!` }
    ],
    '個人差E': [
        { name: `DUE TOMORROW` },
        { name: `GRID KNIGHT[L]` },
        { name: `ICARUS` },
        { name: `Innocent Walls[H]` },
        { name: `Innocent Walls` },
        { name: `one or eight` },
        { name: `SCREAM SQUAD` },
        { name: `Steel Edge` },
        { name: `TROOPERS` },
        { name: `桜` },
        { name: `雪月花` }],

    '地力E': [
        { name: `Apocalypse` },
        { name: `Arca` },
        { name: `Carry Me Away` },
        { name: `Colors(radio edit)` },
        { name: `Concertino in Blue` },
        { name: `encounter` },
        { name: `F` },
        { name: `gigadelic[H]` },
        { name: `gigadelic` },
        { name: `glacia` },
        { name: `Go Beyond!!` },
        { name: `Hat Surprise (Season 2)` },
        { name: `invoker` },
        { name: `LASER CRUSTER` },
        { name: `Liberation` },
        { name: `LIGHTNING STRIKES` },
        { name: `Little Star` },
        { name: `moon_child` },
        { name: `NINJA IS DEAD IIDX ver.` },
        { name: `Pārvatī` },
        { name: `Please Welcome Mr.C` },
        { name: `Raspberry Railgun` },
        { name: `RED ZONE[L]` },
        { name: `Summerlights(IIDX Edition)` },
        { name: `Sweet Clapper[L]` },
        { name: `Symmetry` },
        { name: `Todestrieb` },
        { name: `VANESSA` },
        { name: `Venom` },
        { name: `ΕΛΠΙΣ` },
        { name: `黒髪乱れし修羅となりて` },
        { name: `少年A` },
        { name: `千年ノ理` },
        { name: `紅牡丹` }],

    '地力D': [
        { name: `AA` },
        { name: `ALBIDA` },
        { name: `Beat Radiance[L]` },
        { name: `BIGソムタム` },
        { name: `Broken` },
        { name: `Catch Our Fire!` },
        { name: `Double Dribble` },
        { name: `Drastic Dramatic` },
        { name: `DRUNK MONKY` },
        { name: `EVANESCENT` },
        { name: `Feel the Beat` },
        { name: `Fegrix` },
        { name: `fffff` },
        { name: `FIRE FIRE` },
        { name: `GAIA` },
        { name: `Highcharge Divolt` },
        { name: `Kung-fu Empire[L]` },
        { name: `Matt Silver` },
        { name: `Megalara Garuda` },
        { name: `Meissa` },
        { name: `No Border` },
        { name: `ONE AND ONLY` },
        { name: `oratio` },
        { name: `Persephone` },
        { name: `POSSESSION` },
        { name: `PUNISHER` },
        { name: `Rampage` },
        { name: `Rave Cannon` },
        { name: `Say YEEEAHH` },
        { name: `Scripted Connection⇒ A mix` },
        { name: `Silver Bullet` },
        { name: `SOLID STATE SQUAD` },
        { name: `SpaceLand☆TOYBOX` },
        { name: `TIEFSEE` },
        { name: `The Least 100sec` },
        { name: `The Sampling Paradise` },
        { name: `Thunderbolt` },
        { name: `Trill auf G` },
        { name: `True Blue` },
        { name: `Umbral[L]` },
        { name: `V` },
        { name: `紫陽花 -AZISAI-` },
        { name: `天邪鬼` },
        { name: `ÆTHER[L]` },
        { name: `カゴノトリ〜弐式〜` },
        { name: `神のシナリオ` },
        { name: `#CMFLG` },
        { name: `九尾狐夜行` },
        { name: `狂イ咲ケ焔ノ華` },
        { name: `恋する☆宇宙戦争っ！！` },
        { name: `最小三倍完全数` },
        { name: `〆` },
        { name: `聖人の塔` },
        { name: `即席！脳直★ミュージックシステム` },
        { name: `電人、暁に斃れる。` },
        { name: `刃図羅` },
        { name: `表裏一体!?怪盗いいんちょの悩み♥` }],
    '個人差D': [

        { name: `Caterpillar` },
        { name: `dica dica` },
        { name: `eRAseRmOToRpHAntOM` },
        { name: `Fascination MAXX` },
        { name: `Fire Beat` },
        { name: `mosaic` },
        { name: `PLEASE DON'T GO` },
        { name: `魔法のかくれんぼ` },
        { name: `ワルツ第17番 ト短調"大犬のワルツ"` }
    ],

    '個人差C': [
        { name: `Adularia` },
        { name: `B.O.D.Y.` },
        { name: `BLUE MIRAGE` },
        { name: `Level 2` },
        { name: `New Castle Legions` },
        { name: `ONIGOROSHI` },
        { name: `Rave*it!! Rave*it!!` },
        { name: `Sense 2007` },
        { name: `TOGAKUSHI` },
        { name: `ZZ` },
        { name: `スーパー戦湯ババンバーン` },
        { name: `ハイテックトキオ[L]` },
        { name: `海神` }],

    '地力C': [
        { name: `Aftermath` },
        { name: `AKASHIC BREAK` },
        { name: `Always We Trust In You` },
        { name: `Amazing Mirage[L]` },
        { name: `Ancient Scapes` },
        { name: `anthracene` },
        { name: `Arabian Rave Night[L]` },
        { name: `Chaotoxin` },
        { name: `Cosmic Cat[L]` },
        { name: `DARK LEGACY` },
        { name: `dAuntl3ss` },
        { name: `DAY DREAM` },
        { name: `DOMINION` },
        { name: `Dr. Chemical & Killing Machine` },
        { name: `EBONY & IVORY` },
        { name: `Evans` },
        { name: `FANTASTIC THREE` },
        { name: `Friction[!]Function` },
        { name: `FUZIN RIZIN` },
        { name: `Godspeed` },
        { name: `GOLDEN CROSS` },
        { name: `Gravigazer` },
        { name: `Idola` },
        { name: `innocent revolver` },
        { name: `Invitation from Mr.C` },
        { name: `Konzert V` },
        { name: `L.F.O` },
        { name: `Last Dance` },
        { name: `Lethal Weapon` },
        { name: `LIVE DRIVING!! feat. 花たん` },
        { name: `LOST TECHNOLOGIE` },
        { name: `NEO GENERATOR SEVEN` },
        { name: `Nightmare before oversleep` },
        { name: `NNRT` },
        { name: `Push on Beats!～音ゲの国のeX-ストリーマー～` },
        { name: `rage against usual` },
        { name: `RAIN` },
        { name: `Rave Patroller` },
        { name: `RINИE` },
        { name: `rommmo` },
        { name: `SAY BAY` },
        { name: `Sol Cosine Job 2` },
        { name: `SOLID STATE SQUAD -RISEN RELIC REMIX-` },
        { name: `Sounds Of Summer` },
        { name: `spiral galaxy[L]` },
        { name: `Super Freak` },
        { name: `TECHNO Style Essentials` },
        { name: `THANK YOU FOR PLAYING[L]` },
        { name: `THE DAY OF JUBILATIONS` },
        { name: `thunder HOUSE NATION Remix[L]` },
        { name: `Vinculum stellarum` },
        { name: `Viridian` },
        { name: `We're so Happy(P*Light Remix) IIDX ver.` },
        { name: `WONDER WALKER` },
        { name: `Ypsilon[L]` },
        { name: `イザナミノナゲキ` },
        { name: `Ōu Legends` },
        { name: `子供の落書き帳` },
        { name: `疾風迅雷` },
        { name: `シュレーディンガーの猫` },
        { name: `深淵に捧ぐレクイエム` },
        { name: `旋律のドグマ 〜Miserables〜` },
        { name: `それは花火のような恋` },
        { name: `トリカゴノ鳳凰` },
        { name: `夏色DIARY - L.E.D.-G STYLE MIX -` },
        { name: `華爛漫-Flowers-[L]` },
        { name: `禊` },
        { name: `めいさいアイドル☆あいむちゃん♪` },
        { name: `龍王の霊廟(Mausoleum Of The Primal Dragon)[L]` },
        { name: `恋愛＝精度×認識力` }
    ],
    '個人差B': [
        { name: `AO-1` },
        { name: `FAKE TIME` },
        { name: `Flashes` },
        { name: `IMPLANTATION` },
        { name: `Marie Antoinette[L]` },
        { name: `Papilio ulysses` },
        { name: `PARANOiA 〜HADES〜` },
        { name: `Red. by Full Metal Jacket` },
        { name: `VOX UP` },
        { name: `Watch Out Pt.2` },
        { name: `Y&Co. is dead or alive` },
        { name: `アストライアの双皿` },
        { name: `逆月` },
        { name: `雪上断火` },
        { name: `ミラージュ・レジデンス[L]` }
    ],
    '地力B': [
        { name: `AA -rebuild-` },
        { name: `Angel's Ladder` },
        { name: `Arkadia` },
        { name: `ASIAN VIRTUAL REALITIES (MELTING TOGETHER IN DAZZLING DARKNESS)` },
        { name: `BIGWAVERS` },
        { name: `BITTER CHOCOLATE STRIKER` },
        { name: `BLUE DRAGON(雷龍RemixIIDX)` },
        { name: `Broken Sword` },
        { name: `Burning Flame[L]` },
        { name: `Candy Galy` },
        { name: `cinder` },
        { name: `Close the World feat.a☆ru` },
        { name: `CODE:1 [revision 1.0.1]` },
        { name: `Colorful Cookie` },
        { name: `Dances with Snow Fairies` },
        { name: `Devilz Staircase` },
        { name: `DropZ-Line-` },
        { name: `DUAL STRIKER` },
        { name: `entelecheia` },
        { name: `Flying Castle` },
        { name: `GENE` },
        { name: `HARD BRAIN` },
        { name: `I` },
        { name: `Illusionary Waterlily` },
        { name: `INSOMNIA` },
        { name: `KILL EACH OTHER` },
        { name: `LASER CRUSTER (IGNITE REMIX)` },
        { name: `Little Little Princess[L]` },
        { name: `M4K3 1T B0UNC3` },
        { name: `MAX 300` },
        { name: `MAX 360` },
        { name: `Monopole.` },
        { name: `neu` },
        { name: `NITROUS CANNON` },
        { name: `One for All` },
        { name: `OTENAMI Hurricane` },
        { name: `QUANTUM TELEPORTATION[L]` },
        { name: `Proof of the existence` },
        { name: `quaver♪` },
        { name: `ra'am` },
        { name: `refrain` },
        { name: `reunion` },
        { name: `ruin of opals` },
        { name: `Session 9 -Chronicles-` },
        { name: `Sky High` },
        { name: `Slipstream` },
        { name: `Smalt #28598F` },
        { name: `Super Rush` },
        { name: `T-REX vs Velociraptor (In the Far east euphoria)` },
        { name: `THE DEEP STRIKER[L]` },
        { name: `Timepiece phase II` },
        { name: `Triple Cross` },
        { name: `Übertreffen[L]` },
        { name: `Valanga` },
        { name: `Vitrum` },
        { name: `Welcome[L]` },
        { name: `X` },
        { name: `Xlø` },
        { name: `Xperanza` },
        { name: `24h Endurance Race` },
        { name: `ΕΛΠΙΣ[L]` },
        { name: `少年は空を辿る` },
        { name: `神謳 -RESONANCE-` },
        { name: `たまゆら` },
        { name: `童話回廊` },
        { name: `轟け！恋のビーンボール！！` },
        { name: `廿[L]` },
        { name: `儚キ戀ノ幻想譚` },
        { name: `不沈艦CANDY` },
        { name: `#MAGiCVLGiRL_TRVP_B3VTZ` },
        { name: `魅惑のYUMMYスイーツ` },
        { name: `龍と少女とデコヒーレンス[L]` },
        { name: `リリーゼと炎龍レーヴァティン` }],
    '個人差B+': [
        { name: `Be quiet[L]` },
        { name: `Boomy and The Boost` },
        { name: `DIAMOND CROSSING` },
        { name: `GiGaGaHell` },
        { name: `Hollywood Galaxy` },
        { name: `Inferno of Fomalhaut` },
        { name: `Peaktime Booster` },
        { name: `Snake Stick` },
        { name: `STULTI` },
        { name: `水鏡の異界` },
        { name: `焱影` }
    ],
    '地力B+': [
        { name: `ANCHOR` },
        { name: `Antigravity` },
        { name: `DEADHEAT` },
        { name: `Empire of Fury` },
        { name: `fallen leaves -IIDX edition-` },
        { name: `Grand Chariot` },
        { name: `GRAVITON` },
        { name: `JOMANDA` },
        { name: `kors k's How to make OTOGE CORE 「LONG」` },
        { name: `Mächö Mönky` },
        { name: `NEW GENERATION-もう、お前しか見えない-[L]` },
        { name: `One More Lovely` },
        { name: `ORCA` },
        { name: `PLASMA SOUL NIGHT feat. Nana Takahashi / 709sec.` },
        { name: `Shooting Fireball` },
        { name: `Skreaming for Salvation` },
        { name: `Snakey Kung-fu` },
        { name: `STARLIGHT DANCEHALL[L]` },
        { name: `StrayedCatz` },
        { name: `SYNC-ANTHEM` },
        { name: `The Limbo` },
        { name: `TOXIC VIBRATION` },
        { name: `Twelfth Style[L]` },
        { name: `Unbelief` },
        { name: `Visterhv` },
        { name: `YAKSHA` },
        { name: `キャトられ♥恋はモ〜モク` },
        { name: `ぞうしょく！？マイデンティティ` },
        { name: `抱きしめてモナムール` },
        { name: `津軽雪` },
        { name: `東京神話` },
        { name: `†渚の小悪魔ラヴリィ〜レイディオ†(IIDX EDIT)` }
    ],
    '個人差A': [
        { name: `AIR RAID FROM THA UNDAGROUND[L]` },
        { name: `Don't believe the hype` },
        { name: `Level One` },
        { name: `Purple Perplex` },
        { name: `Scripted Connection⇒ A mix[L]` },
        { name: `STEEL NEEDLE[L]` },
        { name: `TECHNOPHOBIA` },
        { name: `199024club -Re:BounceKiller-` },
        { name: `2 Beasts Unchained` },
        { name: `3y3s` },
        { name: `音楽` },
        { name: `バッド・スイーツ、バッド・ドリーム` },
        { name: `ピアノ協奏曲第1番"蠍火"` }
    ],
    '地力A': [
        { name: `ABSOLUTE EVIL` },
        { name: `ALTERNATOR` },
        { name: `Artist` },
        { name: `Bad Maniacs` },
        { name: `BEAT PRISONER` },
        { name: `BLACK or WHITE?` },
        { name: `Blue Rain[L]` },
        { name: `Close the World feat.a☆ru[L]` },
        { name: `COSMIC RAY` },
        { name: `DEATH†ZIGOQ〜怒りの高速爆走野郎〜` },
        { name: `Despair of ELFERIA` },
        { name: `Devil's Gear` },
        { name: `DORNWALD 〜Junge〜` },
        { name: `Dynamite` },
        { name: `Elektrick U-Phoria[L]` },
        { name: `EXUSIA` },
        { name: `Feel The Beat[L]` },
        { name: `four pieces of heaven[L]` },
        { name: `G59` },
        { name: `Ganymede[L]` },
        { name: `GuNGNiR` },
        { name: `HADES` },
        { name: `HAERETICUS` },
        { name: `KAISER PHOENIX` },
        { name: `Life Is A Game ft.DD"ナカタ"Metal` },
        { name: `LOCUS OF THE TRAVEL` },
        { name: `MENDES` },
        { name: `Painful Fate` },
        { name: `quell〜the seventh slave〜` },
        { name: `Secrets[L]` },
        { name: `SOLID STATE SQUAD[L]` },
        { name: `suspicions` },
        { name: `THE BRAVE MUST DIE` },
        { name: `The Rebellion of Sequencer` },
        { name: `Tiempo Loco` },
        { name: `Triple Counter` },
        { name: `TRIUMPH` },
        { name: `Verflucht` },
        { name: `Violet Pulse[L]` },
        { name: `VOLAQUAS` },
        { name: `voltississimo` },
        { name: `waxing and wanding[L]` },
        { name: `ZEPHYRANTHES[L]` },
        { name: `255` },
        { name: `お菓子の王国` },
        { name: `仮想空間の旅人たち[L]` },
        { name: `華麗なる大犬円舞曲` },
        { name: `君のハートにロックオン[L]` },
        { name: `閠槞彁の願い` },
        { name: `金野火織の金色提言` },
        { name: `世界の果てに約束の凱歌を -ReUnion-` },
        { name: `超青少年ノ為ノ超多幸ナ超古典的超舞曲[L]` },
        { name: `天空の夜明け` },
        { name: `伐折羅-vajra-` },
        { name: `ピアノ協奏曲第1番"蠍火" (BlackY Remix)` },
        { name: `二人ノ廃城幽踊宴` },
        { name: `烽火連天の刃` },
        { name: `冥` }],
    '個人差A+': [
        { name: `BLACK.by X-Cross Fade` },
        { name: `invoker[L]` },
        { name: `Level 3` },
        { name: `Level 4` },
        { name: `Red. by Jack Trance` },
        { name: `Reflux` },
        { name: `SCREW // owo // SCREW` },
        { name: `The Chase` },
        { name: `THE PEERLESS UNDER HEAVEN` },
        { name: `Thor's Hammer` },
        { name: `TITANS RETURN[L]` },
        { name: `TOMAHAWK` },
        { name: `Zirkfied` },
        { name: `真 地獄超特急 -HELL or HELL-` },
        { name: `ピアノ独奏無言歌 "灰燼"` }
    ],
    '地力A+': [
        { name: `Almagest` },
        { name: `Ancient Scapes[L]` },
        { name: `Anisakis - somatic mutation type "Forza" - [L]` },
        { name: `B4U(BEMANI FOR YOU MIX)[L]` },
        { name: `Bad Encryption` },
        { name: `Blue Spring Express` },
        { name: `CHRONO DIVER - NORNIR - [L]` },
        { name: `CONTRACT[L]` },
        { name: `Dans la nuit de l'éternité` },
        { name: `EBONY & IVORY[L]` },
        { name: `Ignis†Iræ` },
        { name: `Initiation` },
        { name: `NZM` },
        { name: `PARADISE LOST` },
        { name: `Quakes` },
        { name: `REVOLVER[L]` },
        { name: `Smashing Wedge` },
        { name: `The Clown of 24stairs` },
        { name: `THE F∀UST` },
        { name: `VANESSA[L]` },
        { name: `[ ]DENTITY` },
        { name: `がっつり陰キャ!? 怪盗いいんちょの億劫^^;` },
        { name: `シムルグの目醒め` },
        { name: `∀` },
        { name: `デモーニッシュ[L]` },
        { name: `-65℃` },
        { name: `煉獄のエルフェリア` }
    ],
    '個人差S': [
        { name: `BroGamer[L]` },
        { name: `ECHIDNA` },
        { name: `EROICA` },
        { name: `Lords Of The Roundtable` },
        { name: `Time to Air[L]` },
        { name: `Timepiece phase II(CN Ver.)` },
        { name: `WHA` },
        { name: `ディスコルディア` }],
    '地力S': [
        { name: `Binary Black Hole` },
        { name: `Carmina` },
        { name: `Chrono Diver - PENDULUMs - ` },
        { name: `Confiserie` },
        { name: `Elemental Creation` },
        { name: `EMERALDAS` },
        { name: `Everlasting Message` },
        { name: `Go Ahead!!` },
        { name: `GO OVER WITH GLARE - ROOTAGE 26 - ` },
        { name: `hard - wired` },
        { name: `ICARUS[L]` },
        { name: `KAISER PHOENIX[L]` },
        { name: `MEGAERA` },
        { name: `Override[L]` },
        { name: `perditus†paradisus` },
        { name: `Phoenix[L]` },
        { name: `Sigmund` },
        { name: `Sinus Iridum` },
        { name: `TRANOID[L]` },
        { name: `Xerulean` },
        { name: `栄冠のカンパネラ` },
        { name: `駅猫のワルツ` },
        { name: `焔極OVERKILL` },
        { name: `お米の美味しい炊き方、そしてお米を食べることによるその効果。[L]` },
        { name: `Χ - DEN` },
        { name: `共鳴遊戯の華` },
        { name: `千年ノ理[L]` },
        { name: `IX` },
        { name: `嘆きの樹` }
    ],
    '個人差S+': [
        { name: `DIAVOLO` },
        { name: `Plan 8` },
        { name: `RAGE feat.H14 of LEONAIR` },
        { name: `SAMURAI - Scramble[L]` },
        { name: `灼熱 Pt.2 Long Train Running` },
        { name: `灼熱Beach Side Bunny` }],
    '地力S+': [
        { name: `Beyond Evolution` },
        { name: `GuNGNiR[L]` },
        { name: `Illegal Function Call[L]` },
        { name: `KAMAITACHI[L]` },
        { name: `Mare Nectaris` },
        { name: `n / a` },
        { name: `Sigmund[L]` },
        { name: `Somnidiscotheque` },
        { name: `The Limbo[L]` },
        { name: `Verflucht[L]` },
        { name: `疾風迅雷[L]` },
        { name: `卑弥呼` }],

}

export { tierList };
